name: dice-app
services:
  postgres:
    image: postgres:11.2
    container_name: postgres
    environment:
      POSTGRES_DB: dice
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - target: 5432
        published: 5432
volumes:
  postgres-data:
    name: postgres-data
    driver: local
