name: Lint webapp

on:
  pull_request:
    paths: 
      - webapp/**
  push:
    branches:
      - main
    paths: 
      - webapp/**

jobs:
  eslint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./webapp
    steps:
      - name: Checkout code
        uses: actions/checkout@v4  
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm ci
      - name: Code linting
        run: npm run lint
